#!/usr/bin/env python3
import http

def login():
  tokens = http.GET("http://webcrawler-site.ccs.neu.edu/accounts/login/?next=/fakebook/")
  body = "username=berzsenyi.i&password=74BMDIXZBUIK2EXD&csrfmiddlewaretoken="+tokens["csrfmiddlewaretoken"]+"&next=%2Ffakebook%2F"
  tokens = http.POST("http://webcrawler-site.ccs.neu.edu/accounts/login/", tokens, body)
  return tokens
  
if __name__ == "__main__":
  tokens = login()
