#!/usr/bin/env python3
import http

def login():
  http.GET("http://webcrawler-site.ccs.neu.edu/accounts/login/?next=/fakebook/")

  return 1
if __name__ == "__main__":
  HOST = "webcrawler-site.ccs.neu.edu"
  login()