#!/bin/sh
if [ $1 == "-p" ]
then
	PORT=$2
	if [ $3 == "-s" ]
	then
		S_FLAG=1
	    HOST=$4
    	ID=$5
	else
		S_FLAG=0
	    HOST=$3
    	ID=$4
	fi
else
	PORT=27995
	if [ $1 == "-s" ]
	then
		PORT=27996
		S_FLAG=1
		HOST=$2
		ID=$3
	else
		S_FLAG=0
		HOST=$1
		ID=$2
	fi
fi
python client.py $PORT $S_FLAG $HOST $ID
